Phong shader
JaimeBea/RealBugEngine pull request #18
Opened 2020-12-10 15:46 UTC by lowysole

- Add Phong Material shader
- Add Nodes logic to UI

2020-12-10 15:55 UTC, JaimeBea commented on Game/Shaders/default_fragment.glsl
> +#version 330
#version 460

2020-12-10 15:56 UTC, JaimeBea commented on Game/Shaders/phong_fragment.glsl
> +#version 440
#version 460

2020-12-10 15:57 UTC, JaimeBea commented on Game/Shaders/phong_fragment.glsl
> +    //diffuse
Espacio despues de //

2020-12-10 15:57 UTC, JaimeBea commented on Game/Shaders/phong_fragment.glsl
> +    //specular
Espacio despues de //

2020-12-10 15:58 UTC, JaimeBea commented on Game/Shaders/phong_vertex.glsl
> +#version 440
#version 460

2020-12-10 16:33 UTC, JaimeBea requested changes

2020-12-10 16:33 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +enum class MaterialType
ShaderType es mejor nombre (STANDARD, PHONG)

2020-12-10 16:33 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +	MaterialType material_type = MaterialType::SPECULAR;
shader_type

2020-12-10 16:33 UTC, JaimeBea commented on Project/ComponentMesh.cpp
> +	unsigned vertex_size = position_size * 2 + uv_size;  // Pos + Normal + UV
Mejor position_size + normal_size + uv_size

2020-12-10 16:33 UTC, JaimeBea commented on Project/ComponentMesh.cpp
> +	glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, vertex_size, (void*)(position_size * 2));
position_size + normal_size

2020-12-10 16:33 UTC, JaimeBea commented on Project/ComponentMesh.cpp
> +	unsigned program;
Muévelo a justo antes de inicializarlo

2020-12-10 16:33 UTC, JaimeBea commented on Project/ComponentMesh.cpp
> +	glUniform1i(glGetUniformLocation(program, "diffuse_texture"), 0);
Mejor todas las definiciones de uniforms en el mismo sitio.

2020-12-10 16:33 UTC, JaimeBea commented on Project/ModuleScene.cpp
> +	Load("C:\\Users\\lowys\\Documents\\Master\\Programming\\Assignment_01\\baker_house\\BakerHouse.fbx");
No uses path absoluto

2020-12-10 16:33 UTC, JaimeBea commented on Project/PanelHierarchy.cpp
> +static GameObject* UpdateHierarchyNode(GameObject* game_object, GameObject* selected_object)
Haz la funcion un método privado si lo necesitas. Esto es bastante lioso.

2020-12-10 16:33 UTC, JaimeBea commented on Project/PanelHierarchy.h
> +	GameObject* selected_object = nullptr;
No entiendo esto.

2020-12-10 19:53 UTC, lowysole commented on Project/PanelHierarchy.h
> +	GameObject* selected_object = nullptr;
Es para tener traqueado el game_object seleccionado, lo utilizara panelInspector para mostrar la info

2020-12-10 19:59 UTC, lowysole reviewed
Reviewed and changed

2020-12-10 20:30 UTC, JaimeBea requested changes

2020-12-10 20:30 UTC, JaimeBea commented on Game/Shaders/phong_fragment.glsl
> +    color.rgb  = ambient + diffuse + specular;
Sobra un espacio antes del igual

2020-12-10 20:30 UTC, JaimeBea commented on Game/Shaders/phong_vertex.glsl
> +	frag_normal = transpose(inverse(mat3(model)))*normal;
Faltan espacios alrededor del *

2020-12-10 20:30 UTC, JaimeBea commented on Project/PanelHierarchy.h
> +	GameObject* selected_object = nullptr;
Vale, falta un public: para separarlo de los métodos (es lo mismo pero queda más bonito)

2020-12-10 20:30 UTC, JaimeBea commented on Project/PanelInspector.cpp
> +			return;
No me gusta que hagas return aqui. Lo has hecho bien pero puede haber errores si alguien cambia el código. Puedes usar el DEFER si quieres o invertir el if.

2020-12-10 20:30 UTC, JaimeBea commented on Project/PanelInspector.cpp
> +		// Clamp Values
Los clamps no están demasiado bien.

1. Usas <= y >= a la vez. Usa <= y > o < y >=.
2. Estás convirtiendo 180 en 0 en el 3er y 4º casos.

2020-12-10 20:30 UTC, JaimeBea commented on Project/PanelInspector.cpp
> +		for (std::vector<ComponentMaterial*>::iterator it = materials.begin(); it != materials.end(); it++)
Usa for-each en lugar de iteradores siempre que sea posible, es mucho más legible:

for (ComponentMaterial* material : materials)

2020-12-10 20:30 UTC, JaimeBea commented on Project/PanelInspector.cpp
> +					const char* material_types_current = material_types[int((*it)->material_type)];
Por estilo, usa "(int) variable" en lugar de "int(variable)".

2020-12-11 11:42 UTC, lowysole commented on Project/PanelInspector.cpp
> +		// Clamp Values
Era una prueba, sacado

2020-12-11 11:49 UTC, lowysole reviewed
Reviewed

2020-12-11 11:53 UTC, JaimeBea approved these changes

2020-12-11 14:45 UTC, merged