Add PBR Phong Shaders / Add UI settings
JaimeBea/RealBugEngine pull request #38
Opened 2020-12-28 15:49 UTC by lowysole

2020-12-28 15:50 UTC, lowysole commented
Keeping previous Shaders for now inside the project (to do some tests if needed to compare the differences)

2020-12-29 13:41 UTC, JaimeBea requested changes

2020-12-29 13:41 UTC, JaimeBea commented on Game/Shaders/phong_pbr_fragment.glsl
> +    vec3 frag_n = normalize(frag_normal);
Problemas de formato

2020-12-29 13:41 UTC, JaimeBea commented on Game/Shaders/phong_pbr_vertex.glsl
> + gl_Position = proj * view * model * vec4(pos, 1.0);
2 espacios en lugar de 4

2020-12-29 13:41 UTC, JaimeBea commented on Project/ComponentMaterial.cpp
> +				ImGui::Text("");
¿Por qué texto vacío?

2020-12-29 13:41 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		unsigned diffuse_map;
Variable sin inicializar

2020-12-29 13:41 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		unsigned specular_map;
Variable sin inicializar

2020-12-29 13:41 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		int has_diffuse_map = 1;
Debería ser un bool.

2020-12-29 13:41 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		int has_specular_map = 0;
Debería ser un bool.

2020-12-29 13:41 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		int shininess_alpha = 0;
Debería ser un bool. Mal nombre de variable.

2020-12-29 13:41 UTC, JaimeBea commented on Project/ModuleTextures.cpp
> +	glTexImage2D(GL_TEXTURE_2D, 0, GL_SRGB8_ALPHA8, ilGetInteger(IL_IMAGE_WIDTH), ilGetInteger(IL_IMAGE_HEIGHT), 0, ilGetInteger(IL_IMAGE_FORMAT), GL_UNSIGNED_BYTE, ilGetData());
¿Por qué haces esto?

2020-12-30 08:04 UTC, lowysole commented on Project/ComponentMaterial.cpp
> +				ImGui::Text("");
Para que haya un línea en blanco en el UI

2020-12-30 08:06 UTC, lowysole commented on Project/ComponentMaterial.h
> +		int has_diffuse_map = 1;
He copiado la struct de las diapos. Són int para que cuando entre dentro del shader no se tengan que hacer ifs. Pero puedo hacerlas bool y hacer la conversión antes de enviar al shader

2020-12-30 08:06 UTC, lowysole commented on Project/ComponentMaterial.h
> +		int has_specular_map = 0;
He copiado la struct de las diapos. Són int para que cuando entre dentro del shader no se tengan que hacer ifs. Pero puedo hacerlas bool y hacer la conversión antes de enviar al shader

2020-12-30 08:07 UTC, lowysole commented on Project/ComponentMaterial.h
> +		int shininess_alpha = 0;
He copiado la struct de las diapos. Són int para que cuando entre dentro del shader no se tengan que hacer ifs. Pero puedo hacerlas bool y hacer la conversión antes de enviar al shader

2020-12-30 08:08 UTC, lowysole commented on Project/ModuleTextures.cpp
> +	glTexImage2D(GL_TEXTURE_2D, 0, GL_SRGB8_ALPHA8, ilGetInteger(IL_IMAGE_WIDTH), ilGetInteger(IL_IMAGE_HEIGHT), 0, ilGetInteger(IL_IMAGE_FORMAT), GL_UNSIGNED_BYTE, ilGetData());
Para convertir la Textura en espacio Lineal  antes que entre en el shader ( Relacionado con la Gamma correction)

2020-12-30 13:11 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		int has_diffuse_map = 1;
Puedes hacer la conversión con (int) has_diffuse_map. Será más fácil de entender

2020-12-30 13:12 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		int has_specular_map = 0;
Puedes hacer la conversión con (int) has_diffuse_map. Será más fácil de entender

2020-12-30 13:12 UTC, JaimeBea commented on Project/ComponentMaterial.h
> +		int shininess_alpha = 0;
Puedes hacer la conversión con (int) has_diffuse_map. Será más fácil de entender

2020-12-30 13:14 UTC, JaimeBea requested changes

2020-12-30 13:14 UTC, JaimeBea commented on Game/Shaders/phong_pbr_fragment.glsl
>     	vec3 light_n = normalize(light.position - frag_pos);
Sigue habiendo problemas aquí con la indentación.

2020-12-30 13:14 UTC, JaimeBea commented on Game/Shaders/phong_pbr_vertex.glsl
> +   gl_Position = proj * view * model * vec4(pos, 1.0);
3 espacios en lugar de 4

2020-12-30 15:58 UTC, lowysole commented on Game/Shaders/phong_pbr_fragment.glsl
>     	vec3 light_n = normalize(light.position - frag_pos);
En VS y mi terminal se ve bien, ahora miro que no se haya colado un formato raro

2020-12-30 17:29 UTC, JaimeBea approved these changes

2020-12-30 19:03 UTC, merged